#Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#SPDX-License-Identifier: MIT-0
parameters:
  - region: us-east-1
    names:
      - /aws/reference/secretsmanager/abcsecret
dynamodb:
  - table: DynamoDbTable
    hashkey: pKey
    hashkeytype: S
    hashkeyvalue: pKey1
    sortkey: sKey
    sortkeytype: S
    sortkeyvalue: sKey1