#!/bin/bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# No additional configuration is required for .NET Core extension, since it is self-sufficient
echo "Launching custom extension ..."
dotnet /opt/csharp-example-extension.dll
